### ISSUE TITLE
error during configuration and guild/ friends mode not working

### ISSUE THREAD

**Issue by wycedev** [itsneyoa/fragrunning-bot#6]
when initially configuring, i run into this issue:
root@vmd90962:~/fragrunning-bot# node .
```
Failed to open cache dir Error: ENOENT: no such file or directory, mkdir '/root/.minecraft/nmp-cache'
    at Object.mkdirSync (fs.js:1013:3)
    at MsAuthFlow.initTokenCaches (/root/fragrunning-bot/node_modules/minecraft-protocol/src/client/authFlow.js:44:12)
    at new MsAuthFlow (/root/fragrunning-bot/node_modules/minecraft-protocol/src/client/authFlow.js:34:10)
    at Object.authenticateDeviceCode (/root/fragrunning-bot/node_modules/minecraft-protocol/src/client/microsoftAuth.js:108:18)
    at Object.createClient (/root/fragrunning-bot/node_modules/minecraft-protocol/src/createClient.js:41:21)
    at Object.createBot (/root/fragrunning-bot/node_modules/mineflayer/lib/loader.js:88:35)
    at App.createBotConnection (/root/fragrunning-bot/src/App.js:24:23)
    at App.start (/root/fragrunning-bot/src/App.js:17:21)
    at /root/fragrunning-bot/index.js:18:11 {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/root/.minecraft/nmp-cache'
}
```
not sure if that what leads to the other issue which is the bot accepting group invited from anyone even if set on friends mode

**Comment by itsneyoa** [comment]
`ENOENT: no such file or directory` means that while trying to create a cache to store the access token (stored at `~/.minecraft/npm-cache`) one of the leading folders was not found. This will crash the bot rather than accepting party invites from anyone. I'll look into the friends mode not working and try to fix.
